import { gridToRects } from './sprites.js';

// 12 x 12 pixel icons. '.' is transparent; other letters map to the icon's palette.
const pad = (rows) => [...rows, ...Array(12 - rows.length).fill('.'.repeat(12))];

export const RAW_ICONS = {
  sword: {
    palette: { c: '#ffffff', a: '#cfd8e3', y: '#f2b632', k: '#7a3d00' },
    rows: pad([
      '.....ca.....',
      '.....ca.....',
      '.....ca.....',
      '.....ca.....',
      '.....ca.....',
      '.....ca.....',
      '.....ca.....',
      '...yyyyyy...',
      '.....kk.....',
      '.....kk.....',
      '....kkkk....',
    ]),
  },
  shield: {
    palette: { a: '#5b8def', c: '#cfe0ff', y: '#f2b632' },
    rows: pad([
      '..yyyyyyyy..',
      '.yaaaaaaaay.',
      '.yaaccccaay.',
      '.yaaccccaay.',
      '.yaaaccaaay.',
      '.yaaaccaaay.',
      '..yaaccaay..',
      '..yaaccaay..',
      '...yaaaay...',
      '....yaay....',
      '.....yy.....',
    ]),
  },
  hammer: {
    palette: { a: '#9aa8bd', c: '#e2e8f0', k: '#a5622a', d: '#6b3a12' },
    rows: pad([
      '.aaaaaaaaaa.',
      '.acccccccca.',
      '.aaaaaaaaaa.',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....dd.....',
    ]),
  },
  wand: {
    palette: { y: '#ffd84a', k: '#8b5cf6' },
    rows: pad([
      '.....yy.....',
      '....yyyy....',
      '.yyyyyyyyyy.',
      '....yyyy....',
      '.....yy.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
      '.....kk.....',
    ]),
  },
  bomb: {
    palette: { k: '#2b2b3a', c: '#8fa3c7', a: '#5a6b8f', y: '#ffd84a' },
    rows: pad([
      '........y.y.',
      '.......y.y..',
      '......kk....',
      '....kkkkkk..',
      '...kccakkkk.',
      '..kcakkkkkk.',
      '..kkkkkkkkk.',
      '..kkkkkkkkk.',
      '..kkkkkkkkk.',
      '...kkkkkkk..',
      '....kkkkk...',
    ]),
  },
  heart: {
    palette: { a: '#ff6b8b', c: '#ffc2d0' },
    rows: pad([
      '............',
      '..aaa..aaa..',
      '.aaaaaaaaaa.',
      '.acaaaaaaaa.',
      '.aaaaaaaaaa.',
      '..aaaaaaaa..',
      '...aaaaaa...',
      '....aaaa....',
      '.....aa.....',
    ]),
  },
  bolt: {
    palette: { y: '#ffd84a' },
    rows: pad([
      '......yyyy..',
      '.....yyyy...',
      '....yyyy....',
      '...yyyyyyy..',
      '......yyy...',
      '.....yyy....',
      '....yyy.....',
      '....yy......',
      '...yy.......',
      '...y........',
    ]),
  },
  hourglass: {
    palette: { k: '#e7be80', a: '#9ec9ff', y: '#ffd84a' },
    rows: pad([
      '.kkkkkkkkkk.',
      '..kaaaaaak..',
      '...kaaaak...',
      '....kaak....',
      '.....kk.....',
      '.....kk.....',
      '....kyyk....',
      '...kyyyyk...',
      '..kyyyyyyk..',
      '.kkkkkkkkkk.',
    ]),
  },
  crown: {
    palette: { y: '#ffd84a', r: '#ff5c7a', k: '#c47a12' },
    rows: pad([
      '............',
      '.yy..yy..yy.',
      '.yy..yy..yy.',
      '.yyy.yy.yyy.',
      '.yyyyyyyyyy.',
      '.yyryyyyryy.',
      '.yyyyyyyyyy.',
      '.kkkkkkkkkk.',
    ]),
  },
  bubble: {
    palette: { a: '#f5efe4', k: '#16365d' },
    rows: pad([
      '............',
      '..aaaaaaaa..',
      '.aaaaaaaaaa.',
      '.aaaaaaaaaa.',
      '.aakaakaaka.',
      '.aaaaaaaaaa.',
      '..aaaaaaaa..',
      '...aa.......',
      '..a.........',
    ]),
  },
  book: {
    palette: { k: '#8b5cf6', a: '#f5efe4' },
    rows: pad([
      '............',
      '.kkkkkkkkkk.',
      '.kaaakkaaak.',
      '.kaaakkaaak.',
      '.kaaakkaaak.',
      '.kaaakkaaak.',
      '.kaaakkaaak.',
      '.kaaakkaaak.',
      '.kkkkkkkkkk.',
    ]),
  },
};

export const ICON_RECTS = Object.fromEntries(
  Object.entries(RAW_ICONS).map(([name, def]) => [name, gridToRects(def.rows, def.palette)])
);
